# Generated by Django 4.2.13 on 2024-07-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_comprobante', models.TextField()),
                ('ruc_emisor', models.TextField()),
                ('razon_social_emisor', models.TextField()),
                ('fecha_emision', models.DateField()),
                ('identificacion_receptor', models.TextField()),
                ('subtotal_15', models.FloatField(null=True)),
                ('subtotal_0', models.FloatField(null=True)),
                ('iva', models.FloatField(null=True)),
                ('importe_total', models.FloatField()),
            ],
        ),
    ]
